/**
 * Anarmani Distribution Centre - Consumer Application Portal
 * Frontend logic (cloud version).
 *
 * PDFs upload DIRECTLY to Supabase Storage using signed URLs generated by the
 * backend — the file bytes never pass through the server. Metadata is then
 * saved to the cloud Postgres database via JSON API calls.
 */

(function () {
  'use strict';

  const OFFICE_NAME = 'Anarmani Distribution Centre';

  // -------------------------------------------------------------------------
  // DOM references
  // -------------------------------------------------------------------------
  const els = {
    tbody: document.getElementById('apps-tbody'),
    totalApps: document.getElementById('total-apps'),
    pendingCount: document.getElementById('pending-count'),
    tableInfo: document.getElementById('table-info'),
    emptyState: document.getElementById('empty-state'),
    noResults: document.getElementById('no-results'),
    pagination: document.getElementById('pagination'),
    pageInfo: document.getElementById('page-info'),
    prevPage: document.getElementById('prev-page'),
    nextPage: document.getElementById('next-page'),

    filterSearch: document.getElementById('filter-search'),
    filterFiscalYear: document.getElementById('filter-fiscal-year'),
    filterStatus: document.getElementById('filter-status'),
    clearSearch: document.getElementById('clear-search'),
    btnNewApplication: document.getElementById('btn-new-application'),

    modal: document.getElementById('app-modal'),
    form: document.getElementById('app-form'),
    modalTitle: document.getElementById('modal-title'),
    appId: document.getElementById('app-id'),
    existingScannedPdf: document.getElementById('existing-scanned-pdf'),
    existingInspectionPdf: document.getElementById('existing-inspection-pdf'),
    fiscalYear: document.getElementById('fiscal-year'),
    applicantName: document.getElementById('applicant-name'),
    applicantPhone: document.getElementById('applicant-phone'),
    dartaNumber: document.getElementById('darta-number'),
    scannedPdf: document.getElementById('scanned-pdf'),
    inspectionPdf: document.getElementById('inspection-pdf'),
    scannedPreview: document.getElementById('scanned-preview'),
    inspectionPreview: document.getElementById('inspection-preview'),
    scannedError: document.getElementById('scanned-error'),
    progressStatus: document.getElementById('progress-status'),
    submitBtn: document.getElementById('submit-btn'),
    btnText: document.querySelector('#submit-btn .btn-text'),
    btnLoader: document.querySelector('#submit-btn .btn-loader'),
    formStatus: document.getElementById('form-status'),
    uploadProgress: document.getElementById('upload-progress'),
    uploadProgressFill: document.getElementById('upload-progress-fill'),
    uploadProgressText: document.getElementById('upload-progress-text'),
    toastContainer: document.getElementById('toast-container'),
  };

  // -------------------------------------------------------------------------
  // State
  // -------------------------------------------------------------------------
  let currentPage = 1;
  const PAGE_SIZE = 50;
  let filters = { q: '', fiscalYear: '', status: '' };

  /** Storage paths currently bound to the form (existing on edit, or newly uploaded). */
  let currentScannedPath = null;
  let currentInspectionPath = null;
  /** Storage paths uploaded this modal session but not yet saved (orphan cleanup on cancel). */
  let pendingUploads = [];

  const PROGRESS_STATUSES = ['Pending', 'Under Review', 'Site Inspection Pending', 'Approved', 'Rejected', 'On Hold'];

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------
  function escapeHtml(value) {
    const div = document.createElement('div');
    div.textContent = value == null ? '' : String(value);
    return div.innerHTML;
  }

  function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  function formatDate(value) {
    if (!value) return '—';
    const date = new Date(value.replace(' ', 'T'));
    if (isNaN(date.getTime())) return value;
    return date.toLocaleString(undefined, {
      year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
    });
  }

  function statusClass(status) {
    return 'status-' + String(status).toLowerCase().replace(/\s+/g, '-');
  }

  // -------------------------------------------------------------------------
  // Toasts
  // -------------------------------------------------------------------------
  function showToast(title, message, type = 'info') {
    const icon = type === 'success' ? '✅' : type === 'error' ? '⚠️' : type === 'warning' ? '⚠️' : 'ℹ️';
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `
      <span class="toast-icon" aria-hidden="true">${icon}</span>
      <div class="toast-content">
        <div class="toast-title">${escapeHtml(title)}</div>
        ${message ? `<div class="toast-message">${escapeHtml(message)}</div>` : ''}
      </div>
    `;
    els.toastContainer.appendChild(toast);
    setTimeout(() => {
      toast.classList.add('hiding');
      toast.addEventListener('animationend', () => toast.remove());
    }, 4000);
  }

  // -------------------------------------------------------------------------
  // API helpers
  // -------------------------------------------------------------------------
  async function apiFetch(url, options = {}) {
    const res = await fetch(url, options);
    let data = {};
    try { data = await res.json(); } catch (_) {}
    if (!res.ok) throw new Error(data.error || `Request failed (HTTP ${res.status})`);
    return data;
  }

  // -------------------------------------------------------------------------
  // PDF upload (direct to Supabase Storage via signed URL)
  // -------------------------------------------------------------------------
  async function signUpload(filename, kind) {
    return apiFetch('/api/uploads/sign', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ filename, kind }),
    });
  }

  function putFile(url, file) {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('PUT', url);
      xhr.setRequestHeader('Content-Type', 'application/pdf');
      xhr.setRequestHeader('x-upsert', 'true');
      xhr.upload.addEventListener('progress', (e) => {
        if (e.lengthComputable && file.__onProgress) file.__onProgress(e.loaded);
      });
      xhr.onload = () => resolve();
      xhr.onerror = () => reject(new Error('Network error during upload'));
      xhr.onabort = () => reject(new Error('Upload aborted'));
      xhr.send(file);
    });
  }

  /** Upload one PDF to storage; returns its storage path. */
  async function uploadPdf(file, kind, onProgress) {
    const { url, path: storagePath } = await signUpload(file.name, kind);
    file.__onProgress = onProgress;
    await putFile(url, file);
    return storagePath;
  }

  function discardPendingUploads() {
    const paths = pendingUploads.slice();
    pendingUploads = [];
    paths.forEach((p) => {
      fetch('/api/uploads/delete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ path: p }),
      }).catch(() => {});
    });
  }

  // -------------------------------------------------------------------------
  // Data loading
  // -------------------------------------------------------------------------
  async function fetchApplications() {
    try {
      const params = new URLSearchParams({
        q: filters.q, fiscalYear: filters.fiscalYear, status: filters.status,
        page: String(currentPage), limit: String(PAGE_SIZE),
      });
      const data = await apiFetch(`/api/applications?${params}`);
      renderTable(data);
      updateStats(data.pagination.total);
    } catch (err) {
      showToast('Failed to load', err.message, 'error');
    }
  }

  async function fetchFilters() {
    try {
      const years = await apiFetch('/api/fiscal-years').catch(() => []);
      els.filterFiscalYear.innerHTML = '<option value="">All Fiscal Years</option>' +
        years.map((y) => `<option value="${escapeHtml(y)}">${escapeHtml(y)}</option>`).join('');

      const statuses = await apiFetch('/api/progress-statuses').catch(() => PROGRESS_STATUSES);
      els.filterStatus.innerHTML = '<option value="">All Statuses</option>' +
        statuses.map((s) => `<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join('');
    } catch (err) {
      console.error('Failed to load filters:', err);
    }
  }

  // -------------------------------------------------------------------------
  // Rendering
  // -------------------------------------------------------------------------
  function renderTable(data) {
    const apps = data.applications || [];
    const pagination = data.pagination || { total: 0, page: 1, totalPages: 1 };

    els.tbody.innerHTML = '';
    els.emptyState.hidden = true;
    els.noResults.hidden = true;
    els.pagination.hidden = true;

    if (apps.length === 0) {
      if (filters.q || filters.fiscalYear || filters.status) els.noResults.hidden = false;
      else els.emptyState.hidden = false;
      els.tableInfo.textContent = 'No applications';
      return;
    }

    apps.forEach((app, i) => els.tbody.appendChild(createRow(app, (pagination.page - 1) * PAGE_SIZE + i + 1)));

    els.tableInfo.textContent = `${pagination.total} application${pagination.total === 1 ? '' : 's'} found`;

    if (pagination.totalPages > 1) {
      els.pagination.hidden = false;
      els.pageInfo.textContent = `Page ${pagination.page} of ${pagination.totalPages}`;
      els.prevPage.disabled = pagination.page <= 1;
      els.nextPage.disabled = pagination.page >= pagination.totalPages;
    }
  }

  function highlightText(text, term) {
    const escaped = escapeHtml(text);
    if (!term) return escaped;
    const re = new RegExp(escapeRegExp(term), 'ig');
    return escaped.replace(re, (m) => `<mark class="match-highlight">${m}</mark>`);
  }

  function createRow(app, index) {
    const tr = document.createElement('tr');
    const term = filters.q.trim();

    const tdId = document.createElement('td');
    tdId.className = 'cell-id';
    tdId.textContent = index;

    const tdYear = document.createElement('td');
    tdYear.className = 'cell-year';
    tdYear.innerHTML = highlightText(app.fiscal_year, term);

    const tdName = document.createElement('td');
    tdName.className = 'cell-name';
    tdName.innerHTML = highlightText(app.applicant_name, term);

    const tdPhone = document.createElement('td');
    tdPhone.className = 'cell-phone';
    tdPhone.innerHTML = highlightText(app.applicant_phone, term);

    const tdDarta = document.createElement('td');
    tdDarta.className = 'cell-darta';
    tdDarta.innerHTML = highlightText(app.darta_number, term);

    const tdScanned = document.createElement('td');
    tdScanned.innerHTML = app.scanned_pdf_url
      ? `<a class="doc-link" href="${app.scanned_pdf_url}" target="_blank" rel="noopener">📄 View</a>`
      : `<span class="doc-link none">—</span>`;

    const tdInspection = document.createElement('td');
    tdInspection.innerHTML = app.inspection_pdf_url
      ? `<a class="doc-link" href="${app.inspection_pdf_url}" target="_blank" rel="noopener">📋 View</a>`
      : `<span class="doc-link none">—</span>`;

    const tdStatus = document.createElement('td');
    tdStatus.innerHTML = `<span class="status-badge ${statusClass(app.progress_status)}">${escapeHtml(app.progress_status)}</span>`;

    const tdDate = document.createElement('td');
    tdDate.className = 'cell-date';
    tdDate.textContent = formatDate(app.created_at);

    const tdActions = document.createElement('td');
    tdActions.className = 'cell-actions';
    tdActions.innerHTML = `
      <button class="action-btn edit" data-id="${app.id}" title="Edit" aria-label="Edit application">✏️</button>
      <button class="action-btn delete" data-id="${app.id}" title="Delete" aria-label="Delete application">🗑️</button>
    `;

    tr.append(tdId, tdYear, tdName, tdPhone, tdDarta, tdScanned, tdInspection, tdStatus, tdDate, tdActions);
    return tr;
  }

  function updateStats(total) {
    els.totalApps.textContent = `${total} Application${total === 1 ? '' : 's'}`;
  }

  // -------------------------------------------------------------------------
  // Modal handling
  // -------------------------------------------------------------------------
  function openModal(app = null) {
    els.form.reset();
    clearFormErrors();
    els.formStatus.textContent = '';
    els.formStatus.className = 'form-status';
    showProgressBar(false);
    pendingUploads = [];

    if (app) {
      els.modalTitle.textContent = 'Edit Application';
      els.appId.value = app.id;
      els.fiscalYear.value = app.fiscal_year;
      els.applicantName.value = app.applicant_name;
      els.applicantPhone.value = app.applicant_phone;
      els.dartaNumber.value = app.darta_number;
      els.progressStatus.value = app.progress_status;

      currentScannedPath = app.scanned_pdf_path || null;
      currentInspectionPath = app.inspection_pdf_path || null;
      els.existingScannedPdf.value = currentScannedPath || '';
      els.existingInspectionPdf.value = currentInspectionPath || '';

      els.scannedPdf.required = !currentScannedPath;
      setPreviewFile(els.scannedPreview, currentScannedPath, 'scanned');
      setPreviewFile(els.inspectionPreview, currentInspectionPath, 'inspection');
    } else {
      els.modalTitle.textContent = `New Application — ${OFFICE_NAME}`;
      els.appId.value = '';
      currentScannedPath = null;
      currentInspectionPath = null;
      els.existingScannedPdf.value = '';
      els.existingInspectionPdf.value = '';
      els.scannedPdf.required = true;
      els.scannedPreview.hidden = true;
      els.inspectionPreview.hidden = true;
      els.scannedPreview.querySelector('.preview-name').textContent = '';
      els.inspectionPreview.querySelector('.preview-name').textContent = '';
    }

    els.modal.showModal();
  }

  function closeModal() {
    discardPendingUploads(); // delete any uploaded-but-unsaved PDFs
    els.modal.close();
  }

  function setPreviewFile(previewEl, storagePath, kind) {
    const nameEl = previewEl.querySelector('.preview-name');
    if (storagePath) {
      const fname = storagePath.split('/').pop();
      nameEl.textContent = `Current: ${fname}`;
      previewEl.hidden = false;
    } else {
      previewEl.hidden = true;
      nameEl.textContent = '';
    }
  }

  function clearFormErrors() {
    els.form.querySelectorAll('.invalid').forEach((el) => el.classList.remove('invalid'));
    els.scannedError.hidden = true;
  }

  function showFormStatus(message, type) {
    els.formStatus.textContent = message;
    els.formStatus.className = 'form-status' + (type ? ' ' + type : '');
  }

  function setLoading(loading) {
    els.submitBtn.disabled = loading;
    els.btnText.hidden = loading;
    els.btnLoader.hidden = !loading;
  }

  function showProgressBar(show, pct = 0) {
    els.uploadProgress.hidden = !show;
    els.uploadProgressFill.style.width = `${Math.round(pct * 100)}%`;
    els.uploadProgressText.textContent = `Uploading PDFs… ${Math.round(pct * 100)}%`;
  }

  // -------------------------------------------------------------------------
  // Form submit (create / update) — uploads PDFs, then saves JSON metadata
  // -------------------------------------------------------------------------
  async function handleSubmit(e) {
    e.preventDefault();
    clearFormErrors();

    const id = els.appId.value;
    const fiscalYear = els.fiscalYear.value.trim();
    const applicantName = els.applicantName.value.trim();
    const applicantPhone = els.applicantPhone.value.trim();
    const dartaNumber = els.dartaNumber.value.trim();
    const progressStatus = els.progressStatus.value;

    const scannedFile = els.scannedPdf.files[0];
    const inspectionFile = els.inspectionPdf.files[0];

    // Validation
    let firstInvalid = null;
    if (!fiscalYear) firstInvalid = firstInvalid || els.fiscalYear;
    if (!applicantName) firstInvalid = firstInvalid || els.applicantName;
    if (!applicantPhone) firstInvalid = firstInvalid || els.applicantPhone;
    if (!dartaNumber) firstInvalid = firstInvalid || els.dartaNumber;

    const hasScanned = scannedFile || currentScannedPath;
    if (!hasScanned) {
      els.scannedError.hidden = false;
      els.scannedError.textContent = 'Scanned document PDF is required.';
      firstInvalid = firstInvalid || els.scannedPdf;
    }
    if (scannedFile && scannedFile.type !== 'application/pdf') {
      els.scannedError.hidden = false;
      els.scannedError.textContent = 'Only PDF files are allowed.';
      firstInvalid = firstInvalid || els.scannedPdf;
    }
    if (inspectionFile && inspectionFile.type !== 'application/pdf') {
      showFormStatus('Inspection file must be a PDF.', 'error');
      firstInvalid = firstInvalid || els.inspectionPdf;
    }

    if (firstInvalid) {
      [els.fiscalYear, els.applicantName, els.applicantPhone, els.dartaNumber].forEach((el) => {
        if (!el.value.trim()) el.classList.add('invalid');
      });
      firstInvalid.focus();
      showFormStatus('Please fill in all required fields.', 'error');
      return;
    }

    setLoading(true);

    // 1) Upload new PDFs directly to Supabase Storage
    let scannedPdfPath = currentScannedPath;
    let inspectionPdfPath = currentInspectionPath;
    try {
      const tasks = [];
      if (scannedFile) tasks.push({ file: scannedFile, kind: 'scanned' });
      if (inspectionFile) tasks.push({ file: inspectionFile, kind: 'inspection' });

      if (tasks.length) {
        showProgressBar(true, 0);
        const uploadedBytes = new Array(tasks.length).fill(0);
        const totalBytes = tasks.reduce((s, t) => s + t.file.size, 0);

        const results = await Promise.all(
          tasks.map(async (t, i) => {
            const p = await uploadPdf(t.file, t.kind, (loaded) => {
              uploadedBytes[i] = loaded;
              const done = uploadedBytes.reduce((a, b) => a + b, 0);
              showProgressBar(true, totalBytes ? done / totalBytes : 0);
            });
            pendingUploads.push(p);
            return { kind: t.kind, path: p };
          })
        );

        results.forEach((r) => {
          if (r.kind === 'scanned') scannedPdfPath = r.path;
          else inspectionPdfPath = r.path;
        });
      }

      // 2) Save metadata to the cloud database
      const url = id ? `/api/applications/${id}` : '/api/applications';
      const method = id ? 'PUT' : 'POST';
      const data = await apiFetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fiscalYear, applicantName, applicantPhone, dartaNumber, progressStatus,
          scannedPdfPath, inspectionPdfPath,
        }),
      });

      // Saved — remove these paths from orphan tracking
      pendingUploads = pendingUploads.filter((p) => p !== scannedPdfPath && p !== inspectionPdfPath);

      showToast(id ? 'Application updated' : 'Application created', `${applicantName} — ${dartaNumber}`, 'success');
      els.modal.close();
      await fetchApplications();
    } catch (err) {
      showFormStatus('⚠️ ' + err.message, 'error');
    } finally {
      setLoading(false);
      showProgressBar(false);
    }
  }

  // -------------------------------------------------------------------------
  // Delete
  // -------------------------------------------------------------------------
  async function deleteApplication(id) {
    if (!confirm('Are you sure you want to delete this application? This will also remove its uploaded PDFs.')) return;
    try {
      await apiFetch(`/api/applications/${id}`, { method: 'DELETE' });
      showToast('Application deleted', '', 'success');
      await fetchApplications();
    } catch (err) {
      showToast('Delete failed', err.message, 'error');
    }
  }

  async function loadApplicationForEdit(id) {
    try {
      const app = await apiFetch(`/api/applications/${id}`);
      openModal(app);
    } catch (err) {
      showToast('Failed to load', err.message, 'error');
    }
  }

  // -------------------------------------------------------------------------
  // File input previews
  // -------------------------------------------------------------------------
  function setupFilePreview(input, previewEl, isRequiredField) {
    input.addEventListener('change', () => {
      const f = input.files[0];
      const nameEl = previewEl.querySelector('.preview-name');
      if (f) {
        if (f.type !== 'application/pdf') {
          nameEl.textContent = '⚠ Not a PDF';
          previewEl.hidden = false;
        } else {
          nameEl.textContent = `Selected: ${f.name}`;
          previewEl.hidden = false;
        }
        input.classList.remove('invalid');
        if (isRequiredField) els.scannedError.hidden = true;
      } else {
        previewEl.hidden = true;
        nameEl.textContent = '';
      }
    });

    const removeBtn = previewEl.querySelector('.preview-remove');
    if (removeBtn) {
      removeBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        input.value = '';
        previewEl.hidden = true;
        previewEl.querySelector('.preview-name').textContent = '';
      });
    }
  }

  // -------------------------------------------------------------------------
  // Event listeners
  // -------------------------------------------------------------------------
  function setupEventListeners() {
    els.btnNewApplication.addEventListener('click', () => openModal());

    els.modal.querySelectorAll('.modal-close, .modal-cancel').forEach((btn) => {
      btn.addEventListener('click', closeModal);
    });
    els.modal.addEventListener('click', (e) => {
      if (e.target === els.modal) closeModal();
    });

    els.form.addEventListener('submit', handleSubmit);

    let searchTimer;
    els.filterSearch.addEventListener('input', () => {
      els.clearSearch.hidden = els.filterSearch.value === '';
      clearTimeout(searchTimer);
      searchTimer = setTimeout(() => {
        filters.q = els.filterSearch.value;
        currentPage = 1;
        fetchApplications();
      }, 250);
    });

    els.clearSearch.addEventListener('click', () => {
      els.filterSearch.value = '';
      els.clearSearch.hidden = true;
      filters.q = '';
      currentPage = 1;
      fetchApplications();
      els.filterSearch.focus();
    });

    els.filterFiscalYear.addEventListener('change', () => {
      filters.fiscalYear = els.filterFiscalYear.value;
      currentPage = 1;
      fetchApplications();
    });
    els.filterStatus.addEventListener('change', () => {
      filters.status = els.filterStatus.value;
      currentPage = 1;
      fetchApplications();
    });

    els.prevPage.addEventListener('click', () => {
      if (currentPage > 1) { currentPage--; fetchApplications(); }
    });
    els.nextPage.addEventListener('click', () => {
      currentPage++;
      fetchApplications();
    });

    els.tbody.addEventListener('click', (e) => {
      const editBtn = e.target.closest('.action-btn.edit');
      const delBtn = e.target.closest('.action-btn.delete');
      if (editBtn) loadApplicationForEdit(editBtn.dataset.id);
      else if (delBtn) deleteApplication(delBtn.dataset.id);
    });

    setupFilePreview(els.scannedPdf, els.scannedPreview, true);
    setupFilePreview(els.inspectionPdf, els.inspectionPreview, false);

    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && els.modal.open) closeModal();
    });
  }

  // -------------------------------------------------------------------------
  // Init
  // -------------------------------------------------------------------------
  setupEventListeners();
  fetchFilters();
  fetchApplications();
})();
